<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Extensions.Configuration">
      <HintPath>..\..\..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\9.0.12\ref\net9.0\Microsoft.Extensions.Configuration.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
