// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Data;

#nullable disable

namespace UserManagement.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.Models.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AffectedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AffectedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("UserManagement.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateOfBirth = new DateTime(1984, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "system.user@example.com",
                            Forename = "System",
                            IsActive = true,
                            JobTitle = "System User Account",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "User"
                        },
                        new
                        {
                            Id = 2L,
                            DateOfBirth = new DateTime(1984, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jonny.wilson@inflo.com",
                            Forename = "Jonny",
                            IsActive = true,
                            JobTitle = "Senior Software Engineer",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Wilson"
                        },
                        new
                        {
                            Id = 3L,
                            DateOfBirth = new DateTime(1968, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bfgates@example.com",
                            Forename = "Benjamin Franklin",
                            IsActive = true,
                            JobTitle = "Database Administrator",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Gates"
                        },
                        new
                        {
                            Id = 4L,
                            DateOfBirth = new DateTime(1991, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ctroy@example.com",
                            Forename = "Castor",
                            IsActive = false,
                            JobTitle = "Lead Platform Architect",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Troy"
                        },
                        new
                        {
                            Id = 5L,
                            DateOfBirth = new DateTime(1979, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mraines@example.com",
                            Forename = "Memphis",
                            IsActive = true,
                            JobTitle = "Customer Success Manager",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Raines"
                        },
                        new
                        {
                            Id = 6L,
                            DateOfBirth = new DateTime(1995, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sgodspeed@example.com",
                            Forename = "Stanley",
                            IsActive = true,
                            JobTitle = "Head of Customer Success",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Goodspeed"
                        },
                        new
                        {
                            Id = 7L,
                            DateOfBirth = new DateTime(1982, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "himcdunnough@example.com",
                            Forename = "H.I.",
                            IsActive = true,
                            JobTitle = "Product Manager",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "McDunnough"
                        },
                        new
                        {
                            Id = 8L,
                            DateOfBirth = new DateTime(1973, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cpoe@example.com",
                            Forename = "Cameron",
                            IsActive = false,
                            JobTitle = "Platform Engineer",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Poe"
                        },
                        new
                        {
                            Id = 9L,
                            DateOfBirth = new DateTime(1988, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emalus@example.com",
                            Forename = "Edward",
                            IsActive = false,
                            JobTitle = "Product Manager",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Malus"
                        },
                        new
                        {
                            Id = 10L,
                            DateOfBirth = new DateTime(1965, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dmacready@example.com",
                            Forename = "Damon",
                            IsActive = false,
                            JobTitle = "Working Papers Product Owner",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Macready"
                        },
                        new
                        {
                            Id = 11L,
                            DateOfBirth = new DateTime(1992, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jblaze@example.com",
                            Forename = "Johnny",
                            IsActive = true,
                            JobTitle = "Senior Account Manager",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Blaze"
                        },
                        new
                        {
                            Id = 12L,
                            DateOfBirth = new DateTime(1959, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rfeld@example.com",
                            Forename = "Robin",
                            IsActive = true,
                            JobTitle = "Talent Aquisition Specialis",
                            Organisation = "Inflo",
                            PasswordHash = "",
                            PasswordSalt = "",
                            Surname = "Feld"
                        });
                });

            modelBuilder.Entity("UserManagement.Models.Log", b =>
                {
                    b.HasOne("UserManagement.Models.User", "AffectedUser")
                        .WithMany()
                        .HasForeignKey("AffectedUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("UserManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AffectedUser");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
